### ISSUE TITLE
Doesn't Build on OS/X Mojave (10.14.6)

### ISSUE THREAD

**Issue by dmuth** [doomjs/wadcmd#1]
Hi!  I've been in a bit of a retro game mood lately, and have been playing lots of doom.  As part of that journey, I tried installing your `wadcmd` tool.  Unfortunately, the install process bails with this error.

```
/usr/local/bin/wadcmd -> /usr/local/lib/node_modules/wadcmd/cli.js

> ogg@1.2.6 install /usr/local/lib/node_modules/wadcmd/node_modules/ogg
> node-gyp rebuild

  CC(target) Release/obj.target/libogg/deps/libogg/src/framing.o
  CC(target) Release/obj.target/libogg/deps/libogg/src/bitwise.o
  LIBTOOL-STATIC Release/ogg.a
  CXX(target) Release/obj.target/ogg/src/binding.o
../src/binding.cc:62:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(1, argv);
              ^
../../nan/nan.h:1741:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:76:54: error: too few arguments to function call, single argument 'context' was not specified
  long size = static_cast<long>(info[2]->NumberValue());

```

I installed `node-gyp` and verified that it was in the path, but the same error.  Judging by the messages I'm seeing, a library used by `wadcmd` has been deprecated.

If you need any other info from me or have some troubleshooting I can do, just let me know!

Thanks,

-- Doug
